---
- name: Transfer and execute a script.
  hosts: "freeswitch"
  become: yes
  become_method: sudo
  roles:
    - telegraf

  vars_prompt:
    - name: "index"
      prompt: "freeswitch"
      private: no
    - name: "freeswitch-ansible"
      prompt: "Enter comma separated list of app names"
      private: no

  vars:
    prometheus_pushgateway_enable: True
    prometheus_local_exporter_url: http://localhost:29273/metrics
    pushgateway_url: "https://pushgateway.zbtest.dashbase.io"
    prometheus_pushgateway_url: https://{{ pushgateway_url }}/metrics/job/filebeat/instance/{{ ansible_hostname }}
    nightwatch_version: 1.1.1-rc4
    nightwatch_configs: ""
