dashbase_version: nightly

https: true

enablePodPriority: true

default_storageclass_provider:
  platform: "aws"

v2:
  bucket: MYBUCKET

default:
  storage:
    class: "dashbase-meta"
    size: 20Gi
  containerConfig:
    resources:
      requests:
        cpu: 1
        memory: 2G
      limits:
        cpu: 1
        memory: 2G
  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: "dashbase-data"
      size: "1500Gi"

    containerConfig:
      resources:
        requests:
          cpu: 3.5
          memory: 26G
        limits:
          cpu: 3.5
          memory: 26G
    environment:
      JAVA_OPTS: "-Xmx20g -Xms20g"
      IGNORE_PARSE_FAILURE: true
      BLOOM_FILTER_SIZE: "400"
      MAX_BUFFER_DELAY_IN_SEC: "1000"
      RETENTION_NUM_DAYS: "7"
      RETENTION_SIZE_GB: "1250"
      READER_CACHE_MEM_PERCENT: "60"
      NUM_INDEXING_THREADS: "2"

presto:
  enabled: false
  priorityClassName: dashbase-normal-priority
  presto:
    prestoKeystorePassword: PRESTO_KEYSTORE_PASSWORD
    dashbaseKeystorePassword: DASHBASE_KEYSTORE_PASSWORD

ingress:
  enabled: true
  certmanager: false
  host: test.dashbase.io

etcd_cluster:
  enabled: true
  priorityClassName: dashbase-high-priority
  replicas: 3

filebeat:
  enabled: false
  priorityClassName: dashbase-normal-priority
  elasticsearch_url: https://table-system:7888

# V1_tables

tablesv2:
  LOGS:
    table_manager:
      priorityClassName: dashbase-high-priority
      replicas: 1
      containerConfig:
        resources:
          requests:
            cpu: 1
            memory: 6G
          limits:
            cpu: 1
            memory: 6G
    indexer:
      priorityClassName: dashbase-high-priority
      replicas: 1
      containerConfig:
        resources:
          requests:
            cpu: INXCPU
            memory: INXMEMG
          limits:
            cpu: INXCPU
            memory: INXMEMG

services:
  etcd:
    enabled: false
    priorityClassName: dashbase-high-priority
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 1G
        requests:
          cpu: 900m
          memory: 1G

  auth:
    #AUTH_SET
    enabled: false
    priorityClassName: dashbase-high-priority
    environment:
      DASHBASE_WEB_URL: https://web.test.dashbase.io
      ENABLE_SSL: 'false'
      INTERNAL_TOKEN: "TOKENSTRING"
      REST_URL: http://rest-auth:9478/login/basic

  api:
    expose: false
    enabled: true
    priorityClassName: dashbase-high-priority
    environment:
      #API_ENV
      ENABLE_K8S_DISCOVERY: "true"
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 2G
        requests:
          cpu: 1
          memory: 2G

  syslog:
    enabled: false
    priorityClassName: dashbase-normal-priority
    image: dashbase/fluentd:nightly
    imagePullPolicy: Always
    environment:
      SYSLOG_ELASTICSEARCH_HOSTS: https://table-LOGS:7888
#     SYSLOG_MESSAGE_PARSER: "{\"_message_parser\":{\"type\":\"grok\",\"pattern\":\"%{HTTPD_COMBINEDLOG}\"}}"
#     SYSLOG_MESSAGE_FORMAT: rfc5424

  web:
    expose: true
    enabled: true
    priorityClassName: dashbase-high-priority
    secrets:
      presto-cert:
        dir: /run/prestojks/
        file: presto-cert.pem
      presto-key:
        dir: /run/prestojks/
        file: presto-key.pem
      presto-keystore:
        dir: /run/prestojks/
        file: presto-keystore
      presto-keystore-password:
        dir: /run/prestojks/
        file: presto-keystore-password
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 2G
        requests:
          cpu: 500m
          memory: 2G
    environment:
      #WEB_ENV
      ENABLE_SEARCH_SCHEDULER: "true"
      ENABLE_CHRONOLOGICAL_SORT: "true"
      ENABLE_SCHEDULED_METRICS: "true"
      DISPLAY_COLOREDFIELDS: "from.sip-uri.user,to.sip-uri.user,call-id,level"
      ENABLE_CALL: "false"
      CALL_TABLES: "LOGS"
      #CALLFLOW_TYPE: "SIP"
      SIP_PAGE: "false"
      CDR_PAGE: "false"
      ENABLE_UCAAS: "false"
      ENABLE_APPS: "false"
      ENABLE_APPS_NETSAPIENS: "false"
      UCAAS_PROMETHEUS_URL: "http://prometheus:9090"
#     UCAAS_PRESTO_URL: "jdbc:presto://presto-coordinator-0.presto-coordinator.dashbase.svc.cluster.local:8443/thrift/dashbase?user=test&password=&SSL=true&SSLKeyStorePath=/run/prestojks/presto-keystore&SSLKeyStorePassword=PRESTO_KEYSTORE_PASSWORD"

  prometheus:
    enabled: true
    priorityClassName: dashbase-high-priority
  # image: "dashbase/prometheus:nightly"
    imagePullPolicy: Always
    storage:
      class: "dashbase-meta"
      size: 20Gi
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 2G
        requests:
          cpu: 1
          memory: 2G
  # prometheus_env_variable

  grafana:
    enabled: true
    priorityClassName: dashbase-high-priority
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 2G
        requests:
          cpu: 1
          memory: 2G
  alertmanager:
    enabled: false
    priorityClassName: dashbase-normal-priority
    containerConfig:
      resources:
        limits:
          cpu: 100m
          memory: 0.1G
        requests:
          cpu: 100m
          memory: 0.1G
  pushgateway:
    enabled: true
    priorityClassName: dashbase-normal-priority
    containerConfig:
      resources:
        limits:
          cpu: 1
          memory: 2G
        requests:
          cpu: 1
          memory: 2G
  searcher:
    enabled: true
    priorityClassName: dashbase-high-priority
    replicas: 2
    containerConfig:
      resources:
        requests:
          cpu: 4
          memory: 8G
        limits:
          cpu: 4
          memory: 8G
  exporter:
    enabled: false
    priorityClassName: dashbase-high-priority
    config:
      metrics:
        ucaas_unique_leg_count:
          description: "ucaas unique call legs"
          table: "LOGS"
          accumulate: false
          filter: "type:sip"
          aggregation: "topn(hostname, 100, topn(user-agent, 100, cardinality(call-id)))"

