dashbase_version: nightly

https: true

enablePodPriority: true

default_storageclass_provider:
  platform: "aws"

v2:
  bucket: MYBUCKET

default:
  storage:
    class: "dashbase-meta"
    size: 20Gi

  table:
    priorityClassName: dashbase-high-priority
    storage:
      class: "dashbase-data"
      size: "20Gi"
    environment:
      JAVA_OPTS: "-Xmx2g -Xms2g"
      BLOOM_FILTER_SIZE: "400"
      MAX_BUFFER_DELAY_IN_SEC: "1000"
      RETENTION_NUM_DAYS: "7"
      RETENTION_SIZE_GB: "8"
      READER_CACHE_MEM_PERCENT: "60"
      NUM_INDEXING_THREADS: "2"
      INTERNAL_TOKEN: "TOKENSTRING"

presto:
  enabled: false
  priorityClassName: dashbase-normal-priority
  presto:
    prestoKeystorePassword: PRESTO_KEYSTORE_PASSWORD
    dashbaseKeystorePassword: DASHBASE_KEYSTORE_PASSWORD

ingress:
  enabled: true
  certmanager: false
  includetable: true
  ingresstable: false
  host: test.dashbase.io

etcd_cluster:
  enabled: true
  priorityClassName: dashbase-high-priority
  replicas: 3

filebeat:
  enabled: false
  priorityClassName: dashbase-normal-priority
  elasticsearch_url: https://table-system:7888

metrics-server:
  enabled: false

vertical-pod-autoscaler:
  enabled: false

# V1_tables

tablesv2:
  LOGS:
    table_manager:
      memoryAutoScaler:
        enabled: false
        min: MINMEMTBLMAN
        max: MAXMEMTBLMAN
      priorityClassName: dashbase-high-priority
      replicas: 1
    indexer:
      priorityClassName: dashbase-high-priority
      replicas: 1
      horizontalpodautoscaler:
        enabled: false
      containerConfig:
        resources:
          requests:
            cpu: INXCPU
            memory: INXMEMG
          limits:
            cpu: INXCPU
            memory: INXMEMG

services:
  etcd:
    enabled: false
    priorityClassName: dashbase-high-priority

  auth:
    #AUTH_SET
    enabled: false
    priorityClassName: dashbase-high-priority
    environment:
      DASHBASE_WEB_URL: https://web.test.dashbase.io
      ENABLE_SSL: 'false'
      INTERNAL_TOKEN: "TOKENSTRING"
      REST_URL: http://rest-auth:9478/login/basic

  api:
    expose: false
    enabled: true
    priorityClassName: dashbase-high-priority
    environment:
      #API_ENV
      ENABLE_K8S_DISCOVERY: "true"

  syslog:
    enabled: false
    priorityClassName: dashbase-normal-priority
    image: dashbase/fluentd:nightly
    imagePullPolicy: Always
    environment:
      SYSLOG_ELASTICSEARCH_HOSTS: https://table-LOGS:7888
#     SYSLOG_MESSAGE_PARSER: "{\"_message_parser\":{\"type\":\"grok\",\"pattern\":\"%{HTTPD_COMBINEDLOG}\"}}"
#     SYSLOG_MESSAGE_FORMAT: rfc5424

  web:
    expose: true
    enabled: true
    priorityClassName: dashbase-high-priority
    #PRESTO_SECRETS
    environment:
      #WEB_ENV
      ENABLE_SEARCH_SCHEDULER: "true"
      ENABLE_CHRONOLOGICAL_SORT: "true"
      ENABLE_SCHEDULED_METRICS: "true"
      DISPLAY_COLOREDFIELDS: "from.sip-uri.user,to.sip-uri.user,call-id,level"
      ENABLE_CALL: "false"
      CALL_TABLES: "LOGS"
      #CALLFLOW_TYPE: "SIP"
      SIP_PAGE: "false"
      CDR_PAGE: "false"
      ENABLE_UCAAS: "false"
      ENABLE_APPS: "false"
      ENABLE_APPS_NETSAPIENS: "false"
      UCAAS_PROMETHEUS_URL: "http://prometheus:9090"
#     UCAAS_PRESTO_URL: "jdbc:presto://presto-coordinator-0.presto-coordinator.dashbase.svc.cluster.local:8443/thrift/dashbase?user=test&password=&SSL=true&SSLKeyStorePath=/run/prestojks/presto-keystore&SSLKeyStorePassword=PRESTO_KEYSTORE_PASSWORD"

  prometheus:
    enabled: true
    priorityClassName: dashbase-high-priority
  # image: "dashbase/prometheus:nightly"
    imagePullPolicy: Always
    storage:
      class: "dashbase-meta"
      size: 20Gi
   # prometheus_env_variable

  grafana:
    enabled: true
    priorityClassName: dashbase-high-priority

  alertmanager:
    enabled: false
    priorityClassName: dashbase-normal-priority

  pushgateway:
    enabled: true
    priorityClassName: dashbase-normal-priority

  searcher:
    enabled: true
    priorityClassName: dashbase-high-priority
    replicas: 1

  exporter:
    enabled: false
    priorityClassName: dashbase-high-priority
    config:
      metrics:
        ucaas_unique_leg_count:
          description: "ucaas unique call legs"
          table: "LOGS"
          accumulate: false
          filter: "type:sip"
          aggregation: "topn(hostname, 100, topn(user-agent, 100, cardinality(call-id)))"

